edition = "2021"
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true